name: myapp-proxy

services:
  caddy:
    build:
      context: ./caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
    environment:
      CADDY_SITE_ADDRESS: backend.myapp.com

volumes:
  caddy_data:
    name: caddy-data # Persistent volume for certificates
